# Generated by Django 5.1.6 on 2025-02-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gdpr_int',
            field=models.IntegerField(default=0),
        ),
    ]
